[build]
  base = "."
  publish = "dist"
  command = "npm run build"

[dev]
  command = "npm run dev"
  port = 5000
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/ws"
  to = "/.netlify/functions/ws"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200