[build]
  base = "."
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"

[dev]
  command = "npm run dev"
  port = 5000
  publish = "dist"

[functions]
  external_node_modules = ["express", "ws"]
  node_bundler = "esbuild"
  directory = "netlify/functions"

[functions.api]
  included_files = ["server/**", "shared/**"]

[functions.ws]
  included_files = ["server/**", "shared/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/ws"
  to = "/.netlify/functions/ws"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

